#include <stdio.h>
#include "reply.h"


int main() {
    REPLY r;
    CreateREPLY(&r);
    STRING text, author, text2, author2;
    createString(&text, "Hari ini hari Jumat");
    createString(&author, "Bang Burbir Merajuk");
    createString(&text2, "Radio ga ga");
    createString(&author2, "Freddie");
    DATETIME now = getCurrentDATETIME();
    AddressReply temp1 = newReply(1, text, author, now);
    AddressReply temp2 = newReply(2, text, author, now);
    AddressReply temp3 = newReply(3, text, author, now);
    AddressReply temp4 = newReply(4, text, author, now);
    AddressReply temp5 = newReply(5, text, author, now);
    AddressReply temp6 = newReply(6, text, author, now);
    AddressReply temp7 = newReply(7, text, author, now);
    AddressReply temp8 = newReply(8, text, author, now);
    AddressReply temp9 = newReply(9, text, author, now);
    AddressReply temp10 = newReply(10, text, author, now);
    AddressReply temp11 = newReply(11, text2, author2, now);
    AddressReply temp12 = newReply(12, text2, author2, now);
    AddressReply temp13 = newReply(13, text2, author2, now);
    AddressReply temp14 = newReply(14, text2, author2, now);
    AddressReply temp15 = newReply(15, text2, author2, now);
    AddressReply temp16 = newReply(16, text2, author2, now);
    AddressReply temp17 = newReply(17, text2, author2, now);
    AddressReply temp18 = newReply(18, text2, author2, now);
    AddressReply temp19 = newReply(19, text2, author2, now);
    boolean succeded = false;
    addREPLY(&r, -1, temp1,&succeded);
    succeded = false;
    addREPLY(&r, -1, temp2,&succeded);
    succeded = false;
    addREPLY(&r, -1, temp3,&succeded);
    succeded = false;
    addREPLY(&r, 1, temp4,&succeded);
    succeded = false;
    addREPLY(&r, 4, temp5,&succeded);
    succeded = false;
    addREPLY(&r, 5, temp6,&succeded);
    succeded = false;
    addREPLY(&r, 6, temp7,&succeded);
    succeded = false;
    addREPLY(&r, 5, temp8,&succeded);
    succeded = false;
    addREPLY(&r, 5, temp9,&succeded);
    succeded = false;
    addREPLY(&r, 1, temp10,&succeded);
    succeded = false;
    addREPLY(&r, -1, temp11,&succeded);
    succeded = false;
    addREPLY(&r, 4, temp12,&succeded);
    succeded = false;
    addREPLY(&r, 3, temp13,&succeded);
    succeded = false;
    addREPLY(&r, 13, temp14,&succeded);
    succeded = false;
    addREPLY(&r, 10, temp15,&succeded);
    succeded = false;
    addREPLY(&r, 5, temp16,&succeded);
    succeded = false;
    addREPLY(&r, 11, temp17,&succeded);
    succeded = false;
    addREPLY(&r, 17, temp18,&succeded);
    succeded = false;
    addREPLY(&r, 18, temp19,&succeded);
    displayReply(r, 0);
    succeded = false;
    printf("\n\n ------------------------------ \n\n\n");
    deleteREPLY(&r, 1, &succeded, NULL, NULL);
    displayReply(r,0);
    AddressReply temp20 = newReply(20, text2, author2, now);
    temp1 = newReply(1, text2, author2, now);
    succeded = false;
    addREPLY(&r, -1, temp1,&succeded);
    printf("\n\n ------------------------------ \n\n\n");
    displayReply(r,0);
}
